name: PR CI (Build & Test)

on:
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          cd apps/web && npm install
          
      - name: Type check
        run: |
          cd apps/web
          npm run type-check || true
          
      - name: Build web app
        run: |
          cd apps/web
          npm run build
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies
        run: |
          cd apps/api
          pip install -r requirements.txt
          
      - name: Test API imports
        run: |
          cd apps/api
          python -c "import app.main; print('API imports successful')"

